version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  flask:
    build:
      context: .
      dockerfile: flask.Dockerfile
    ports:
      - "5328:5328"
    environment:
      - FLASK_ENV=production