version: '3.8'

services:
  nextjs:
    image: shuhanmomo/nextjs:latest
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - flask

  flask:
    image: shuhanmomo/flask:latest
    ports:
      - "5328:5328" 
    environment:
      - FLASK_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5328/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge