version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Next.js
      - "5328:5328"  # Flask
    environment:
      - NODE_ENV=production
    command: ["sh", "-c", "pnpm start & python api/index.py"]