name: Deploy App to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify OPENAI_API_KEY
        run: echo "OPENAI_API_KEY starts with: ${OPENAI_API_KEY:0:4}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Next.js Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: node.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nextjs:latest

      - name: Build and push Flask Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: flask.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask:latest
          build-args: |
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Auto Scaling Group to Scale Up
        run: |
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name awseb-e-2q9yi5rnw3-stack-AWSEBAutoScalingGroup-HXdPIbdbQkpo \
            --min-size 1 --max-size 1 --desired-capacity 1 --region ${{ secrets.AWS_REGION }}

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: neural-room-deploy-test
          environment_name: Neural-room-deploy-test-env
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-us-east-2-590183697706
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip

      - name: Scale Down After Deployment
        run: |
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name awseb-e-2q9yi5rnw3-stack-AWSEBAutoScalingGroup-HXdPIbdbQkpo \
            --min-size 0 --max-size 1 --desired-capacity 1 --region ${{ secrets.AWS_REGION }}
