name: Deploy App to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Next.js Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: node.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nextjs:latest

      - name: Build and push Flask Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: flask.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: http://neural-room-deploy-test-env.eba-uwku7g9u.us-east-2.elasticbeanstalk.com/

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: neural-room-deploy-test
          environment_name: Neural-room-deploy-test-env
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-us-east-2-590183697706
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
